/*
 * Function: FLO_fnc_virtualizationCreateGroupRecordDefaults
 * Description:
 *   Single source of truth for the live virtual-group record schema.
 */

createHashMapFromArray [
    ["schemaVersion", 3],
    ["id", ""],
    ["position", [0, 0, 0]],
    ["spawnPosition", [0, 0, 0]],
    ["direction", 0],
    ["groupType", "infantry"],
    ["groupCfg", configNull],
    ["spawnClass", ""],
    ["homeObjective", ""],
    ["unitCount", 0],
    ["side", east],
    ["isActive", false],
    ["alwaysActive", false],
    ["realGroup", grpNull],
    ["realVehicles", []],
    ["state", "idle"],
    ["lastStateChangeTime", diag_tickTime],
    ["inCombat", false],
    ["waypoints", []],
    ["currentWaypointIndex", 0],
    ["autoPatrol", false],
    ["patrolConfig", []],
    ["noWaypoints", false],
    ["idleHelicopterParked", false],
    ["virtualSpeed", 0],
    ["lastMoveTime", -1],
    ["virtualMoveCarryMeters", 0],
    ["loiterStartTime", 0],
    ["pathToken", -1],
    ["pathTargetPos", []],
    ["pathAllowTrails", false],
    ["pathStartedAt", -1],
    ["pathSource", ""],
    ["pathWaypointSettings", []],
    ["vehicleType", ""],
    ["comp", []],
    ["missionLock", ""],
    ["missionType", ""],
    ["replacementState", ""],
    ["activationDeferred", false],
    ["activationDeferredAt", -1],
    ["activationRetryAt", -1],
    ["reinforcementTargetPos", []],
    ["reinforcementRequestedObjective", ""],
    ["reinforcementDeliveryObjective", ""],
    ["forceVirtual", false],
    ["commanderOrder", ""],
    ["executionState", ""],
    ["orderTargetPos", []],
    ["orderMode", ""],
    ["attackObjective", ""],
    ["campaignOperationId", ""],
    ["defendObjective", ""],
    ["defendLeaseIssuedAt", -1],
    ["defendLeaseUntil", -1],
    ["aaDeployState", ""],
    ["aaDeployTargetPos", []],
    ["aaDeployTargetObjective", ""],
    ["isStrategicAA", false],
    ["attachedTo", ""],
    ["attachedGroups", []],
    ["attachedType", ""],
    ["transportRole", false],
    ["isTransport", false],
    ["dismountAtWaypoint", -1],
    ["transportInsertMode", ""],
    ["transportInsertPos", []],
    ["transportLandCommandIssued", false],
    ["transportUnloadCommandIssued", false],
    ["transportUnloadIssuedAt", -1],
    ["postDismountWaypoint", []],
    ["mountedIn", ""],
    ["organicPackageRole", ""],
    ["organicPackageParentGroupId", ""],
    ["garrisonPosition", [0, 0, 0]],
    ["garrisonObjective", ""],
    ["civilianRole", ""],
    ["civilianObjective", ""],
    ["civilianAnchorPos", [0, 0, 0]],
    ["civilianHomeAnchorPos", [0, 0, 0]],
    ["civilianRoutineAnchorPos", [0, 0, 0]],
    ["civilianRouteAnchors", []],
    ["civilianKnowledgeBias", 1],
    ["civilianTrustBias", 1],
    ["civilianLastIntelAt", -1],
    ["civilianLastMood", ""],
    ["civilianRoutineState", ""],
    ["civilianLastRoutineAt", -1],
    ["civilianRoutineUntil", -1],
    ["protestRestoreAlwaysActive", false],
    ["nextProcessAt", 0],
    ["lastProcessedAt", -1]
]
