/*
 * Function: FLO_fnc_virtualizationGetUpdateStatsDefaults
 */

createHashMapFromArray [
    ["cyclesRun", 0],
    ["groupsProcessedTotal", 0],
    ["groupsProcessedThisBatch", 0],
    ["totalGroupsLast", 0],
    ["activeGroupsLast", 0],
    ["inactiveGroupsLast", 0],
    ["activeUnitsLast", 0],
    ["activationCapLast", 0],
    ["deferredGroupsLast", 0],
    ["lastBatchStart", 0],
    ["lastBatchEnd", -1],
    ["lastBatchMs", 0],
    ["peakBatchMs", 0],
    ["lastPlayerCacheMs", 0],
    ["peakPlayerCacheMs", 0],
    ["lastGroupCacheMs", 0],
    ["peakGroupCacheMs", 0],
    ["lastGroupProcessMs", 0],
    ["peakGroupProcessMs", 0],
    ["lastSlowGroupId", ""],
    ["lastSlowGroupType", ""],
    ["lastSlowGroupMs", 0],
    ["activationsTotal", 0],
    ["activationsThisBatch", 0],
    ["activationBlocksTotal", 0],
    ["activationBlocksThisBatch", 0],
    ["deactivationsTotal", 0],
    ["deactivationsThisBatch", 0],
    ["virtualMovesTotal", 0],
    ["virtualMovesThisBatch", 0],
    ["activePositionSyncsTotal", 0],
    ["activePositionSyncsThisBatch", 0],
    ["waypointAdvancesTotal", 0],
    ["waypointAdvancesThisBatch", 0],
    ["patrolAssignmentsTotal", 0],
    ["patrolAssignmentsThisBatch", 0],
    ["attachedSyncsTotal", 0],
    ["attachedSyncsThisBatch", 0],
    ["movementPauseSkipsTotal", 0],
    ["movementPauseSkipsThisBatch", 0],
    ["movementDeadbandSkipsTotal", 0],
    ["movementDeadbandSkipsThisBatch", 0],
    ["missionHoldSkipsTotal", 0],
    ["missionHoldSkipsThisBatch", 0],
    ["eliminatedGroupsTotal", 0],
    ["eliminatedGroupsThisBatch", 0],
    ["stragglerResolvesTotal", 0],
    ["stragglerResolvesThisBatch", 0],
    ["slowBatchCount", 0],
    ["slowGroupCount", 0]
]
