if (isNil "FLO_VirtUpdate") exitWith { [] };

private _stats = FLO_VirtUpdate get "stats";
private _perf = FLO_VirtUpdate get "perf";

[
    ["running", FLO_VirtUpdate get "running"],
    ["pfhId", FLO_VirtUpdate get "pfhId"],
    ["batchSize", FLO_VirtUpdate get "batchSize"],
    ["playerCacheInterval", FLO_VirtUpdate get "playerCacheInterval"],
    ["cachedGroups", count (FLO_VirtUpdate get "cachedGroupIds")],
    ["cachedPlayers", count (FLO_VirtUpdate get "cachedPlayerPositions")],
    ["currentBatchIndex", FLO_VirtUpdate get "currentBatchIndex"],
    ["cyclesRun", _stats get "cyclesRun"],
    ["batchesRunTotal", _stats get "batchesRunTotal"],
    ["batchMsTotal", _stats get "batchMsTotal"],
    ["groupsProcessedTotal", _stats get "groupsProcessedTotal"],
    ["groupsProcessedThisBatch", _stats get "groupsProcessedThisBatch"],
    ["dueGroupsTotal", _stats get "dueGroupsTotal"],
    ["dueGroupsThisBatch", _stats get "dueGroupsThisBatch"],
    ["totalGroupsLast", _stats get "totalGroupsLast"],
    ["activeGroupsLast", _stats get "activeGroupsLast"],
    ["inactiveGroupsLast", _stats get "inactiveGroupsLast"],
    ["lastBatchStart", _stats get "lastBatchStart"],
    ["lastBatchEnd", _stats get "lastBatchEnd"],
    ["lastBatchMs", _stats get "lastBatchMs"],
    ["peakBatchMs", _stats get "peakBatchMs"],
    ["lastPlayerCacheMs", _stats get "lastPlayerCacheMs"],
    ["peakPlayerCacheMs", _stats get "peakPlayerCacheMs"],
    ["lastGroupCacheMs", _stats get "lastGroupCacheMs"],
    ["peakGroupCacheMs", _stats get "peakGroupCacheMs"],
    ["lastGroupProcessMs", _stats get "lastGroupProcessMs"],
    ["peakGroupProcessMs", _stats get "peakGroupProcessMs"],
    ["lastSlowGroupId", _stats get "lastSlowGroupId"],
    ["lastSlowGroupType", _stats get "lastSlowGroupType"],
    ["lastSlowGroupMs", _stats get "lastSlowGroupMs"],
    ["activationsTotal", _stats get "activationsTotal"],
    ["activationsThisBatch", _stats get "activationsThisBatch"],
    ["deactivationsTotal", _stats get "deactivationsTotal"],
    ["deactivationsThisBatch", _stats get "deactivationsThisBatch"],
    ["virtualMovesTotal", _stats get "virtualMovesTotal"],
    ["virtualMovesThisBatch", _stats get "virtualMovesThisBatch"],
    ["activePositionSyncsTotal", _stats get "activePositionSyncsTotal"],
    ["activePositionSyncsThisBatch", _stats get "activePositionSyncsThisBatch"],
    ["waypointAdvancesTotal", _stats get "waypointAdvancesTotal"],
    ["waypointAdvancesThisBatch", _stats get "waypointAdvancesThisBatch"],
    ["patrolAssignmentsTotal", _stats get "patrolAssignmentsTotal"],
    ["patrolAssignmentsThisBatch", _stats get "patrolAssignmentsThisBatch"],
    ["attachedSyncsTotal", _stats get "attachedSyncsTotal"],
    ["attachedSyncsThisBatch", _stats get "attachedSyncsThisBatch"],
    ["movementPauseSkipsTotal", _stats get "movementPauseSkipsTotal"],
    ["movementPauseSkipsThisBatch", _stats get "movementPauseSkipsThisBatch"],
    ["movementDeadbandSkipsTotal", _stats get "movementDeadbandSkipsTotal"],
    ["movementDeadbandSkipsThisBatch", _stats get "movementDeadbandSkipsThisBatch"],
    ["missionHoldSkipsTotal", _stats get "missionHoldSkipsTotal"],
    ["missionHoldSkipsThisBatch", _stats get "missionHoldSkipsThisBatch"],
    ["eliminatedGroupsTotal", _stats get "eliminatedGroupsTotal"],
    ["eliminatedGroupsThisBatch", _stats get "eliminatedGroupsThisBatch"],
    ["stragglerResolvesTotal", _stats get "stragglerResolvesTotal"],
    ["stragglerResolvesThisBatch", _stats get "stragglerResolvesThisBatch"],
    ["phaseSamplesTotal", _stats get "phaseSamplesTotal"],
    ["phaseSampleMsTotal", _stats get "phaseSampleMsTotal"],
    ["phaseProximityMsTotal", _stats get "phaseProximityMsTotal"],
    ["phaseScheduleMsTotal", _stats get "phaseScheduleMsTotal"],
    ["phaseAttachedMsTotal", _stats get "phaseAttachedMsTotal"],
    ["phaseMovementMsTotal", _stats get "phaseMovementMsTotal"],
    ["phasePositionUpdateMsTotal", _stats get "phasePositionUpdateMsTotal"],
    ["phaseCarrierSyncMsTotal", _stats get "phaseCarrierSyncMsTotal"],
    ["phaseActivationMsTotal", _stats get "phaseActivationMsTotal"],
    ["phaseActiveMsTotal", _stats get "phaseActiveMsTotal"],
    ["phaseAttachedHandledTotal", _stats get "phaseAttachedHandledTotal"],
    ["phaseMovementCallsTotal", _stats get "phaseMovementCallsTotal"],
    ["phasePositionUpdatesTotal", _stats get "phasePositionUpdatesTotal"],
    ["phaseHoldingSkipsTotal", _stats get "phaseHoldingSkipsTotal"],
    ["phaseActiveCallsTotal", _stats get "phaseActiveCallsTotal"],
    ["slowBatchCount", _stats get "slowBatchCount"],
    ["slowGroupCount", _stats get "slowGroupCount"],
    ["slowBatchThresholdMs", _perf get "slowBatchThresholdMs"],
    ["slowGroupThresholdMs", _perf get "slowGroupThresholdMs"]
]
